export type Endpoints = {
  "/assistants": {}
  "/assistants/{assistant_id}": {}
  "/audio/speech": {}
  "/audio/transcriptions": {}
  "/audio/translations": {}
  "/batches": {}
  "/batches/{batch_id}": {}
  "/batches/{batch_id}/cancel": {}
  "/chat/completions": {}
  "/chat/completions/{completion_id}": {}
  "/chat/completions/{completion_id}/messages": {}
  "/completions": {}
  "/embeddings": {}
  "/files": {}
  "/files/{file_id}": {}
  "/files/{file_id}/content": {}
  "/fine_tuning/checkpoints/{permission_id}/permissions": {}
  "/fine_tuning/jobs": {}
  "/fine_tuning/jobs/{fine_tuning_job_id}": {}
  "/fine_tuning/jobs/{fine_tuning_job_id}/cancel": {}
  "/fine_tuning/jobs/{fine_tuning_job_id}/checkpoints": {}
  "/fine_tuning/jobs/{fine_tuning_job_id}/events": {}
  "/images/edits": {}
  "/images/generations": {}
  "/images/variations": {}
  "/models": {}
  "/models/{model}": {}
  "/moderations": {}
  "/organization/admin_api_keys": {}
  "/organization/admin_api_keys/{key_id}": {}
  "/organization/audit_logs": {}
  "/organization/costs": {}
  "/organization/invites": {}
  "/organization/invites/{invite_id}": {}
  "/organization/projects": {}
  "/organization/projects/{project_id}": {}
  "/organization/projects/{project_id}/api_keys": {}
  "/organization/projects/{project_id}/api_keys/{key_id}": {}
  "/organization/projects/{project_id}/archive": {}
  "/organization/projects/{project_id}/rate_limits": {}
  "/organization/projects/{project_id}/rate_limits/{rate_limit_id}": {}
  "/organization/projects/{project_id}/service_accounts": {}
  "/organization/projects/{project_id}/service_accounts/{service_account_id}": {}
  "/organization/projects/{project_id}/users": {}
  "/organization/projects/{project_id}/users/{user_id}": {}
  "/organization/usage/audio_speeches": {}
  "/organization/usage/audio_transcriptions": {}
  "/organization/usage/code_interpreter_sessions": {}
  "/organization/usage/completions": {}
  "/organization/usage/embeddings": {}
  "/organization/usage/images": {}
  "/organization/usage/moderations": {}
  "/organization/usage/vector_stores": {}
  "/organization/users": {}
  "/organization/users/{user_id}": {}
  "/realtime/sessions": {}
  "/realtime/transcription_sessions": {}
  "/responses": {}
  "/responses/{response_id}": {}
  "/responses/{response_id}/input_items": {}
  "/threads": {}
  "/threads/runs": {}
  "/threads/{thread_id}": {}
  "/threads/{thread_id}/messages": {}
  "/threads/{thread_id}/messages/{message_id}": {}
  "/threads/{thread_id}/runs": {}
  "/threads/{thread_id}/runs/{run_id}": {}
  "/threads/{thread_id}/runs/{run_id}/cancel": {}
  "/threads/{thread_id}/runs/{run_id}/steps": {}
  "/threads/{thread_id}/runs/{run_id}/steps/{step_id}": {}
  "/threads/{thread_id}/runs/{run_id}/submit_tool_outputs": {}
  "/uploads": {}
  "/uploads/{upload_id}/cancel": {}
  "/uploads/{upload_id}/complete": {}
  "/uploads/{upload_id}/parts": {}
  "/vector_stores": {}
  "/vector_stores/{vector_store_id}": {}
  "/vector_stores/{vector_store_id}/file_batches": {}
  "/vector_stores/{vector_store_id}/file_batches/{batch_id}": {}
  "/vector_stores/{vector_store_id}/file_batches/{batch_id}/cancel": {}
  "/vector_stores/{vector_store_id}/file_batches/{batch_id}/files": {}
  "/vector_stores/{vector_store_id}/files": {}
  "/vector_stores/{vector_store_id}/files/{file_id}": {}
  "/vector_stores/{vector_store_id}/files/{file_id}/content": {}
  "/vector_stores/{vector_store_id}/search": {}
}
