// Generated by `@liminal/sqlite/_codegen.ts`
export const statements = [
  `PRAGMA foreign_keys=OFF;`,
  `
CREATE TABLE IF NOT EXISTS \`__new_threads\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`system\` text,
	\`parent\` text,
	\`head\` text,
	\`clearedAt\` text,
	FOREIGN KEY (\`parent\`) REFERENCES \`events\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`head\`) REFERENCES \`events\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`clearedAt\`) REFERENCES \`events\`(\`id\`) ON UPDATE no action ON DELETE no action
);
`,
  `
INSERT INTO \`__new_threads\`("id", "system", "parent", "head", "clearedAt") SELECT "id", "system", "parent", "head", "clearedAt" FROM \`threads\`;`,
  `
DROP TABLE \`threads\`;`,
  `
ALTER TABLE \`__new_threads\` RENAME TO \`threads\`;`,
  `
PRAGMA foreign_keys=ON;`,
  `CREATE TABLE IF NOT EXISTS \`events\` (
	\`parentId\` text,
	\`id\` text PRIMARY KEY NOT NULL,
	\`threadId\` text NOT NULL,
	\`event\` text NOT NULL,
	\`timestamp\` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	FOREIGN KEY (\`parentId\`) REFERENCES \`events\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`threadId\`) REFERENCES \`threads\`(\`id\`) ON UPDATE no action ON DELETE no action
);
`,
  `
CREATE TABLE IF NOT EXISTS \`messages\` (
	\`parentId\` text,
	\`id\` text PRIMARY KEY NOT NULL,
	\`threadId\` text NOT NULL,
	\`message\` text NOT NULL,
	\`eventId\` text NOT NULL,
	FOREIGN KEY (\`parentId\`) REFERENCES \`messages\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`threadId\`) REFERENCES \`threads\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`eventId\`) REFERENCES \`events\`(\`id\`) ON UPDATE no action ON DELETE no action
);
`,
  `
CREATE TABLE IF NOT EXISTS \`threads\` (
	\`id\` text NOT NULL,
	\`system\` text,
	\`parent\` text,
	\`head\` text,
	\`clearedAt\` text,
	FOREIGN KEY (\`parent\`) REFERENCES \`events\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`head\`) REFERENCES \`events\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`clearedAt\`) REFERENCES \`events\`(\`id\`) ON UPDATE no action ON DELETE no action
);`,
]
