// Generated by `@liminal/sqlite/_codegen.ts`
export const statements = [
  `CREATE TABLE IF NOT EXISTS \`events\` (
	\`parentId\` text,
	\`id\` text PRIMARY KEY NOT NULL,
	\`threadId\` text NOT NULL,
	\`event\` text NOT NULL,
	\`timestamp\` integer DEFAULT (unixepoch() * 1000) NOT NULL
);
`,
  `
CREATE TABLE IF NOT EXISTS \`messages\` (
	\`parentId\` text,
	\`id\` text PRIMARY KEY NOT NULL,
	\`threadId\` text NOT NULL,
	\`message\` text NOT NULL,
	\`eventId\` text NOT NULL
);
`,
  `
CREATE TABLE IF NOT EXISTS \`threads\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`system\` text,
	\`parent\` text,
	\`head\` text
);`,
]
