name: liminal.land
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/configure-pages@v4
      - run: bun i
      - run: bun liminal.land build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: liminal.land/.vitepress/dist
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
