name: Release

on:
  release:
    types: [created]

jobs:
  jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: sed -i s/0.0.0-local.0/${{ github.event.release.tag_name }}/ deno.json
      - run: deno publish --allow-dirty

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno run -A ./tasks/npm.ts --version ${{ github.event.release.tag_name }}
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: target/npm/package-lock.json
          node-version: 21.x
          registry-url: "https://registry.npmjs.org"
      - run: cd target/npm && npm version ${{ github.event.release.tag_name }} --no-git-tag-version --allow-same-version && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
