name: test
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: "tests-${{ github.ref }}"
  cancel-in-progress: false
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - uses: dprint/check@v2.2
      - run: bun run build
      - run: bun test
